import { AppSpec } from '../../types';

export class FlutterGenerator {
  public static generateFlutterFiles(spec: AppSpec): Record<string, string> {
    const files: Record<string, string> = {};
    const pkg = spec.packageName;
    const appName = spec.appName;

    // 1. pubspec.yaml
    files['android/pubspec.yaml'] = `name: ${appName.toLowerCase().replace(/[^a-z0-9_]/g, '_')}
description: "Generated by AppForge AI - ${spec.description.slice(0, 100)}"
publish_to: 'none'
version: ${spec.version}+${spec.versionCode}

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
`;

    // 2. Android Manifest
    files['android/android/app/src/main/AndroidManifest.xml'] = `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${pkg}">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.CAMERA"/>

    <application
        android:label="${appName}"
        android:name="\${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`;

    // 3. Android build.gradle (app-level)
    files['android/android/app/build.gradle'] = `plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '${spec.versionCode}'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '${spec.version}'
}

android {
    namespace "${pkg}"
    compileSdk 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "${pkg}"
        minSdk 24
        targetSdk 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}
`;

    // Root settings.gradle
    files['android/android/settings.gradle'] = `pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        def localPropertiesFile = file("local.properties")
        if (localPropertiesFile.exists()) {
            localPropertiesFile.withInputStream { properties.load(it) }
        }
        return properties.getProperty("flutter.sdk") ?: System.getenv("FLUTTER_ROOT")
    }()

    if (flutterSdkPath != null) {
        includeBuild("\$flutterSdkPath/packages/flutter_tools/gradle")
    }

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.2.1" apply false
    id "org.jetbrains.kotlin.android" version "1.9.22" apply false
}

include ":app"
`;

    // Root build.gradle
    files['android/android/build.gradle'] = `allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "\${rootProject.buildDir}/\${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
`;

    // MainActivity.kt
    const pkgPath = pkg.replace(/\./g, '/');
    files[`android/android/app/src/main/kotlin/${pkgPath}/MainActivity.kt`] = `package ${pkg}

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
`;

    // 4. App Config with Configurable API Base URL
    files['android/lib/core/config/app_config.dart'] = `class AppConfig {
  static const String appName = '${appName}';
  static const String appVersion = '${spec.version}';
  // User-configurable API Base URL (default connects to local host or emulator)
  static String apiBaseUrl = 'http://10.0.2.2/api';
  static const String currency = '${spec.payments.currency}';
  static const int requestTimeoutSeconds = 20;

  static void setApiBaseUrl(String url) {
    apiBaseUrl = url.endsWith('/') ? url.substring(0, url.length - 1) : url;
  }
}
`;

    // 5. App Theme
    files['android/lib/core/theme/app_theme.dart'] = `import 'package:flutter/material.dart';

class AppTheme {
  static const Color primaryColor = Color(${spec.theme.primaryColor.replace('#', '0xFF')});
  static const Color secondaryColor = Color(${spec.theme.secondaryColor.replace('#', '0xFF')});
  static const Color accentColor = Color(${spec.theme.accentColor.replace('#', '0xFF')});
  static const Color backgroundColor = Color(${spec.theme.backgroundColor.replace('#', '0xFF')});

  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: primaryColor,
        primary: primaryColor,
        secondary: secondaryColor,
        background: backgroundColor,
      ),
      scaffoldBackgroundColor: backgroundColor,
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        iconTheme: IconThemeData(color: Colors.black87),
        titleTextStyle: TextStyle(color: Colors.black87, fontSize: 18, fontWeight: FontWeight.bold),
      ),
      cardTheme: CardTheme(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0xFFE2E8F0)),
        ),
      ),
    );
  }
}
`;

    // 6. Network API Client
    files['android/lib/core/network/api_client.dart'] = `import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../config/app_config.dart';

class ApiClient {
  static Future<Map<String, String>> _getHeaders() async {
    final prefs = await SharedPreferences.getInstance();
    final token = prefs.getString('auth_token');
    return {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      if (token != null) 'Authorization': 'Bearer \$token',
    };
  }

  static Future<dynamic> get(String endpoint) async {
    final uri = Uri.parse('\${AppConfig.apiBaseUrl}/\$endpoint');
    final response = await http.get(uri, headers: await _getHeaders())
        .timeout(const Duration(seconds: AppConfig.requestTimeoutSeconds));
    return _processResponse(response);
  }

  static Future<dynamic> post(String endpoint, Map<String, dynamic> body) async {
    final uri = Uri.parse('\${AppConfig.apiBaseUrl}/\$endpoint');
    final response = await http.post(uri, headers: await _getHeaders(), body: jsonEncode(body))
        .timeout(const Duration(seconds: AppConfig.requestTimeoutSeconds));
    return _processResponse(response);
  }

  static dynamic _processResponse(http.Response res) {
    final data = jsonDecode(res.body);
    if (res.statusCode >= 200 && res.statusCode < 300) {
      return data;
    } else {
      throw Exception(data['error'] ?? 'Server error \${res.statusCode}');
    }
  }
}
`;

    // 7. Main Entry Point
    files['android/lib/main.dart'] = `import 'package:flutter/material.dart';
import 'core/theme/app_theme.dart';
import 'features/home/home_screen.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const AppForgeGeneratedApp());
}

class AppForgeGeneratedApp extends StatelessWidget {
  const AppForgeGeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${appName}',
      theme: AppTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      home: const HomeScreen(),
    );
  }
}
`;

    // 8. Home Screen
    files['android/lib/features/home/home_screen.dart'] = `import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../details/detail_screen.dart';
import '../profile/profile_screen.dart';
import '../search/search_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('${appName}'),
        actions: [
          IconButton(
            icon: const Icon(Icons.search),
            onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const SearchScreen())),
          ),
          IconButton(
            icon: const Icon(Icons.notifications_outlined),
            onPressed: () {},
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Hero Banner
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppTheme.primaryColor, AppTheme.secondaryColor],
                ),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Discover & Explore', style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 6),
                  Text('${spec.description.slice(0, 80)}...', style: const TextStyle(color: Colors.white70, fontSize: 13)),
                  const SizedBox(height: 12),
                  ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.white,
                      foregroundColor: AppTheme.primaryColor,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    ),
                    child: const Text('Get Started'),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            // Featured Items Title
            const Text('Featured Collections', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 12),
            // Dynamic Grid
            GridView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: 4,
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                childAspectRatio: 0.8,
                crossAxisSpacing: 12,
                mainAxisSpacing: 12,
              ),
              itemBuilder: (context, index) {
                return GestureDetector(
                  onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => DetailScreen(itemId: index + 1))),
                  child: Card(
                    clipBehavior: Clip.antiAlias,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(
                          child: Container(
                            color: Colors.grey.shade200,
                            child: Center(
                              child: Icon(Icons.image_outlined, size: 40, color: Colors.grey.shade400),
                            ),
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.all(10),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Featured Item #\${index + 1}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                              const SizedBox(height: 4),
                              Text('\${AppTheme.primaryColor.value.toRadixString(16).substring(2, 4)}00 ${spec.payments.currency}', style: const TextStyle(color: AppTheme.primaryColor, fontWeight: FontWeight.w700, fontSize: 13)),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ],
        ),
      ),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _currentIndex,
        onDestinationSelected: (idx) {
          setState(() => _currentIndex = idx);
          if (idx == 3) {
            Navigator.push(context, MaterialPageRoute(builder: (_) => const ProfileScreen()));
          }
        },
        destinations: const [
          NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: 'Home'),
          NavigationDestination(icon: Icon(Icons.explore_outlined), selectedIcon: Icon(Icons.explore), label: 'Explore'),
          NavigationDestination(icon: Icon(Icons.favorite_border), selectedIcon: Icon(Icons.favorite), label: 'Favorites'),
          NavigationDestination(icon: Icon(Icons.person_outline), selectedIcon: Icon(Icons.person), label: 'Profile'),
        ],
      ),
    );
  }
}
`;

    // 9. Detail Screen
    files['android/lib/features/details/detail_screen.dart'] = `import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../checkout/checkout_screen.dart';

class DetailScreen extends StatelessWidget {
  final int itemId;
  const DetailScreen({super.key, required this.itemId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Item #\$itemId Details')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              height: 220,
              width: double.infinity,
              decoration: BoxDecoration(
                color: Colors.grey.shade100,
                borderRadius: BorderRadius.circular(20),
              ),
              child: const Icon(Icons.photo_library_outlined, size: 60, color: Colors.grey),
            ),
            const SizedBox(height: 20),
            Text('Premium Item Listing #\$itemId', style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('Verified Merchant • 4.9 ★ (120 reviews)', style: TextStyle(color: Colors.grey, fontSize: 13)),
            const SizedBox(height: 16),
            const Text('Description', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text(
              'High grade verified item published through the AppForge AI modular ecosystem. Fully synced with MySQL backend and managed via administrative dashboard.',
              style: TextStyle(color: Colors.black87, height: 1.5),
            ),
            const SizedBox(height: 32),
            SizedBox(
              width: double.infinity,
              height: 52,
              child: ElevatedButton(
                onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const CheckoutScreen())),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primaryColor,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                ),
                child: const Text('Proceed to Order / Checkout', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`;

    // 10. Search Screen
    files['android/lib/features/search/search_screen.dart'] = `import 'package:flutter/material.dart';

class SearchScreen extends StatelessWidget {
  const SearchScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const TextField(
          autofocus: true,
          decoration: InputDecoration(
            hintText: 'Search catalog, items, tags...',
            border: InputBorder.none,
          ),
        ),
      ),
      body: const Center(
        child: Text('Type keywords to filter results in real-time', style: TextStyle(color: Colors.grey)),
      ),
    );
  }
}
`;

    // 11. Profile Screen
    files['android/lib/features/profile/profile_screen.dart'] = `import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My Account')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          const Center(
            child: CircleAvatar(
              radius: 44,
              backgroundColor: AppTheme.primaryColor,
              child: Icon(Icons.person, size: 50, color: Colors.white),
            ),
          ),
          const SizedBox(height: 12),
          const Center(child: Text('Active User', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold))),
          const Center(child: Text('user@appforge.local', style: TextStyle(color: Colors.grey, fontSize: 13))),
          const SizedBox(height: 24),
          ListTile(leading: const Icon(Icons.shopping_bag_outlined), title: const Text('My Orders & Transactions'), trailing: const Icon(Icons.chevron_right)),
          ListTile(leading: const Icon(Icons.favorite_border), title: const Text('Saved Favorites'), trailing: const Icon(Icons.chevron_right)),
          ListTile(leading: const Icon(Icons.security_outlined), title: const Text('Security & Password'), trailing: const Icon(Icons.chevron_right)),
          ListTile(leading: const Icon(Icons.help_outline), title: const Text('Support & Privacy'), trailing: const Icon(Icons.chevron_right)),
        ],
      ),
    );
  }
}
`;

    // 12. Checkout Screen
    files['android/lib/features/checkout/checkout_screen.dart'] = `import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';

class CheckoutScreen extends StatefulWidget {
  const CheckoutScreen({super.key});

  @override
  State<CheckoutScreen> createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  String _selectedGateway = 'stripe';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Payment & Checkout')),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Select Payment Method', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            RadioListTile<String>(
              value: 'stripe',
              groupValue: _selectedGateway,
              onChanged: (val) => setState(() => _selectedGateway = val!),
              title: const Text('Credit Card (Stripe Safe Pay)'),
              secondary: const Icon(Icons.credit_card),
            ),
            RadioListTile<String>(
              value: 'paypal',
              groupValue: _selectedGateway,
              onChanged: (val) => setState(() => _selectedGateway = val!),
              title: const Text('PayPal Express'),
              secondary: const Icon(Icons.account_balance_wallet_outlined),
            ),
            RadioListTile<String>(
              value: 'manual',
              groupValue: _selectedGateway,
              onChanged: (val) => setState(() => _selectedGateway = val!),
              title: const Text('Direct Bank Transfer / Cash'),
              secondary: const Icon(Icons.payments_outlined),
            ),
            const Spacer(),
            SizedBox(
              width: double.infinity,
              height: 52,
              child: ElevatedButton(
                onPressed: () {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('Payment order initiated successfully through backend API!')),
                  );
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primaryColor,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                ),
                child: const Text('Confirm Payment', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`;

    return files;
  }
}
